[build]
  command = "npm run build"
  functions = "netlify/functions"
[functions]
  node_bundler = "esbuild"
[context.production]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "src"